---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation Amazon FSx for NetApp ONTAP
    url: "/index.html"
  - title: Notes de version
    url: "/whats-new.html"
  - title: Commencer
    entries:
    - title: En savoir plus sur Amazon FSx for NetApp ONTAP
      url: "/start/concept-fsx-aws.html"
    - title: Démarrage rapide
      url: "/start/task-getting-started-fsx.html"
    - title: Configurer les autorisations
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: Créer ou découvrir un système de fichiers FSx pour ONTAP
      url: "/use/task-create-fsx-system.html"
  - title: Gérer un système de fichiers FSx pour ONTAP
    url: "/use/task-manage-fsx-systems.html"
  - title: Surveiller les opérations avec Tracker
    url: "/use/task-monitor-operations.html"
  - title: Supprimer un système de fichiers d'un projet
    url: "/use/task-remove-filesystem.html"
  - title: Supprimer un système de fichiers FSx pour ONTAP
    url: "/use/task-delete-fsx-system.html"
  - title: Connaissances et soutien
    entries:
    - title: Inscrivez-vous pour obtenir de l'aide
      url: "/support/task-support-registration.html"
    - title: Obtenir de l'aide
      url: "/support/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
