---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, NetApp Console 
summary: Après avoir créé ou découvert un système FSx for ONTAP dans la NetApp Console, vous pouvez gérer le système de fichiers et utiliser les services de données NetApp qui fournissent des fonctionnalités telles que la sauvegarde et la récupération. 
---
= Gérer un système de fichiers FSx pour ONTAP dans la NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Après avoir créé ou découvert un système FSx for ONTAP dans la NetApp Console, vous pouvez gérer le système de fichiers en créant des volumes, en gérant les machines virtuelles de stockage, en protégeant les données et en administrant le système de fichiers.  La console vous permet également d'utiliser des services de données qui offrent des fonctionnalités telles que la sauvegarde et la récupération, la classification des données, la synchronisation des données, etc.



== Gérez un système de fichiers à l'aide de NetApp Workload Factory

Lorsque vous ouvrez un système FSx for ONTAP depuis la page Systèmes de la NetApp Console, vous accédez à NetApp Workload Factory. NetApp Workload Factory est un service intelligent d’optimisation et d’automatisation qui utilise les meilleures pratiques du secteur pour planifier, provisionner et exploiter les charges de travail clés à l’aide d’Amazon FSx for NetApp ONTAP.

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Apprenez à gérer un système de fichiers à l'aide de NetApp Workload Factory"^]



== Gérer un système de fichiers à l'aide d' ONTAP System Manager

Vous pouvez gérer un système de fichiers FSx pour ONTAP directement depuis la console en utilisant l'interface ONTAP System Manager. Un agent Console ou un lien AWS Lambda est requis pour utiliser System Manager.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Apprenez-en davantage sur l'utilisation des liens"^]



== Gérer un système de fichiers à l'aide d'Amazon CloudFormation

Vous pouvez provisionner et gérer les ressources du système de fichiers FSx for ONTAP (volumes, partages CIFS, stratégies d'exportation, etc.) à l'aide d'Amazon CloudFormation.

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["Référentiel GitHub du fournisseur NetApp CloudFormation FSx pour ONTAP"^]



== Utiliser les services de données NetApp avec un système de fichiers

Utilisez les services de données NetApp avec vos systèmes de fichiers FSx for ONTAP pour sauvegarder et récupérer vos données, transférer et synchroniser les données, analyser et classer vos données, répliquer les données et accélérer l'accès ou décharger le trafic.



=== Sauvegardez et récupérez vos données

NetApp Backup and Recovery offre une protection des données efficace, sécurisée et économique pour les données, les bases de données et les machines virtuelles NetApp ONTAP , sur site et dans le cloud.

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Démarrez avec NetApp Backup and Recovery"^]



=== Transférer et synchroniser les données

NetApp Copy and Sync est un service de réplication et de synchronisation cloud permettant de transférer des données NAS entre des magasins d'objets sur site et dans le cloud.

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["Démarrer avec NetApp Copy and Sync"^]



=== Numérisez et classez vos données

NetApp Data Classification vous permet d'analyser et de classer les données dans le multicloud hybride de votre organisation.

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["Démarrer avec la NetApp Data Classification"^]



=== Accélérez l'accès ou déchargez le trafic

NetApp Volume Caching fournit un volume persistant et inscriptible dans un emplacement distant.  Vous pouvez utiliser la mise en cache des volumes pour accélérer l’accès aux données ou pour décharger le trafic des volumes fortement sollicités.

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["Démarrer avec la NetApp Volume Caching"^]
